[game]
hostname = "☢️S.T.A.L.K.E.R. [EN Test] ☣️"
desc = "Server in S.T.A.L.K.E.R. setting. Now in English!"
#map = "STWorld" # st-changes-dev-map
map_pool = "STDefaultMapPool"  # st-changes-map-pool
maxplayers = 80
soft_max_players = 60
map_rotation = false
role_timers = true
peaceful_end = false
# lobbyduration = 10
contraband_examine = false
role_whitelist = true
maxcharacterslots = 1

[server]
default_guide = "STNewPlayer"
rules_file = "STRuleset"

[rules]
time = 10.0

[whitelist]
enabled = false

[shuttle]
auto_call_time = 0
emergency = false
arrivals = false
preload_grids = false
camera_rotation_locked = true

[ic]
flavor_text = true
punctuation = false

[tts]
enabled = false

[infolinks]
discord = "https://discord.gg/SnUSV76zR3"
patreon = "https://boosty.to/stalkerss14"

[hub]
advertise = true
tags = "lang:en,rp:high,region:us_e"
hub_urls = "https://hub.spacestation14.com/"

[events]
enabled = false

#[worldgen]
#enabled = false
#[procgen]
#preload = false

[console]
login_host_user = "coolmankid12345"

[crewmanifest]
no_entity = false
